format = """
[  ]()\
$directory\
$git_branch\
$git_status\
$time\
"""

[directory]
format = "[ $path ](fg:#06b6d4)($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#d946ef)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#d946ef)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#06b6d4)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:#06b6d4)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#06b6d4)]($style)'

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:#06b6d4)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[[  $time ](fg:#10b981)]($style)'
